/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  alexm
 * Created: 28 de mar. de 2023
 */

ETNORRACIAL MESTRADO
UPDATE `candidato` SET `cotas`='er' where nome in ('ADRIELE DE CASSIA DA SILVA SOEIRO', 'AERCIO VALE SILVA', 'ALINE SILVA DE FREITAS', 'AURILENE PEREIRA FERREIRA', 'CARLA ROMANO AMARAL', 'CLAUDIO LEANDRO BARBOSA CARVALHO', 'EMERSON SILVA CALDAS', 'FABRILA DE CÁSSIA SILVA DA ROCHA', 'GESIEL RIBEIRO DE LEÃO', 'GESSICA CRISTINA BARRAL FARIAS AMORIM', 'GYSELLE KOLWALSK CRUZ DE LIMA', 'INGRID GOMES DE FREITAS', 'JAIR FILHO PINTO MENDONÇA', 'JOEL CARLOS SILVA DA SILVA', 'LEANDRO MACHADO DOS SANTOS', 'LUIZ FELIPE DA SILVA FURTADO', 'MARCOS VINICIUS SALES DA SILVA', 'MATHEUS DOS SANTOS BENTO', 'MESSIAS FRANÇA DO NASCIMENTO', 'PAULA THAIS PELAZ DA SILVA', 'RAFAEL BRITO GONZAGA', 'RAPHAEL MENDES DE SOUZA', 'RENATO TEIXEIRA PINHEIRO', 'RUBERVALDO CRUZ SARMENTO FILHO', 'SAMILY MARIA MOREIRA DA SILVA E SILVA', 'SOCORRO CARVALHO DE LIMA', 'SUELLE PAIXÃO REIS', 'TEODORO DA COSTA NEGRÃO NETO', 'THAIS MACHADO RODRIGUES', 'THAYSA CRISTINA MAGALHAES DOS SANTOS', 'URSULA CELESTE TAVARES BAHIA DE JESUS', 'YURI AMORIM DA SILVA', 'LISANDRA ROBERTA MENDONÇA DOS SANTOS') and processo = 48

ETNORRACIAL DOUTORADO
UPDATE `candidato` SET `cotas`='er' where nome in ('MARINA DONZA GUEDES ', 'PATRICH DEPAILLER FERREIRA MORAES', 'ADRIANO BARROSO DOS SANTOS ', 'EVELYN TAINÁ DE SOUZA SILVA', 'IVAL DE ANDRADE PICANÇO NETO', 'LIANA DA SILVA CUNHA', 'MARIA CECI LEAL BANDEIRA', 'MYLENA MONTEIRO SETÚBAL', 'PENELOPE LOPES DE LIMA', 'RUBENS RAFAEL SANTA BRÍGIDA', 'VINICIUS VIANA FERREIRA') and processo = 48

COTA TRANS MESTRADO
UPDATE `candidato` SET `cotas`='ct' where nome in ('ISABELLA VALENTINA CONCEIÇÃO BARROS', 'RAFAEL MATHEUS MOREIRA MONTEIRO') and processo = 48

COTA PADT MESTRADO E DOUTORADO
UPDATE `candidato` SET `cotas`='padt' where nome in ('JAILTON GOMES DA SILVA', 'BRENO FILO CREÃO DE SOUSA GARCIA', 'JORGE LUIS TORRES DE AZEVEDO', 'JOSE EDUARDO PASTANA SILVA', 'PAULO DE TARSO NUNES DOS SANTOS JUNIOR', 'THAYNAH PATRICIA BORGES CONCEIÇÃO PINHEIRO' ) and processo = 48
